refactor web backend
RoCS2024/osd-records-mgt-web-appl pull request #12
Opened 2024-11-07 11:24 UTC by kylmrcdr123

RCPS_177 AND 178 web-backend-maintenance: Create a Function of Get Id by User ID for employee and student

2024-11-07 12:47 UTC, JustineDaveMagnaye approved these changes

2024-11-08 05:40 UTC, PhilippaulDaganio approved these changes

2024-11-08 11:50 UTC, zhairanicolepacheco requested changes
Adjust the Controller accordingly

2024-11-08 11:50 UTC, zhairanicolepacheco commented on src/main/java/com/rocs/osd/service/employee/impl/EmployeeServiceImpl.java
> +            return employee.getId();
it should be 'employee.getEmployeeNumber'

2024-11-08 11:50 UTC, zhairanicolepacheco commented on src/main/java/com/rocs/osd/service/student/impl/StudentServiceImpl.java
> +            return student.getId();
it should be 'employee.getStudentNumber'

2024-11-08 11:50 UTC, zhairanicolepacheco commented on src/main/java/com/rocs/osd/service/student/StudentService.java
> +    Long getStudentIdByUserId(Long userId);
it should be 'getStudentNumberByUserId'

2024-11-08 11:50 UTC, zhairanicolepacheco commented on src/main/java/com/rocs/osd/service/employee/EmployeeService.java
> +    Long getEmployeeIdByUserId(Long userId);
it should be 'getEmployeeNumberByUserId'

2024-11-08 11:50 UTC, zhairanicolepacheco commented on src/main/java/com/rocs/osd/repository/employee/EmployeeRepository.java
> +     * @return employeeId
return employeeNumber

2024-11-08 11:50 UTC, zhairanicolepacheco commented on src/main/java/com/rocs/osd/repository/student/StudentRepository.java
> +     * @return studentId
return studentNumber

2024-11-08 12:19 UTC, esdi-00 commented on src/main/java/com/rocs/osd/controller/employee/EmployeeController.java
> +    @GetMapping("/employeeIdByUserId/{userId}")
why do you need such endpoint?

2024-11-08 12:19 UTC, esdi-00 commented on src/main/java/com/rocs/osd/controller/student/StudentController.java
> +    @GetMapping("/studentIdByUserId/{userId}")
why do you need such endpoint?

2024-11-08 12:20 UTC, esdi-00 commented on src/main/java/com/rocs/osd/repository/employee/EmployeeRepository.java
> +     * @return employeeId
isn't it to return an employee object instead?

2024-11-08 12:20 UTC, esdi-00 commented on src/main/java/com/rocs/osd/repository/student/StudentRepository.java
> +     * @return studentId
isn't it to return an student object instead?

2024-11-08 12:21 UTC, esdi-00 commented on src/main/java/com/rocs/osd/service/employee/EmployeeService.java
> +    Long getEmployeeIdByUserId(Long userId);
But employeeNumber is Long type?

2024-11-08 12:23 UTC, esdi-00 requested changes
see comments

2024-11-08 15:27 UTC, zhairanicolepacheco commented on src/main/java/com/rocs/osd/controller/student/StudentController.java
> +    @GetMapping("/studentIdByUserId/{userId}")
Sir, I ordered Kyla to make an endpoint that retrieves the student number since upon login they are only passing the user ID, but to display the violations, we need the student number since it is the FK of violation

2024-11-11 13:35 UTC, zhairanicolepacheco approved these changes

2024-11-12 07:29 UTC, esdi-00 commented on src/main/java/com/rocs/osd/controller/employee/EmployeeController.java
> +    @GetMapping("/employeeNumberByUserId/{userId}")
I am still puzzled why you have to create an endpoint for getting userId

2024-11-12 07:30 UTC, esdi-00 commented on src/main/java/com/rocs/osd/domain/section/Section.java
> +    private String organization;
what is organization for?

2024-11-12 07:32 UTC, esdi-00 requested changes
please answer in the comments what changes you did to address the issue

2024-11-12 11:06 UTC, kylmrcdr123 commented on src/main/java/com/rocs/osd/controller/employee/EmployeeController.java
> +    @GetMapping("/employeeNumberByUserId/{userId}")
Sir, the student number needs to be obtained using the user ID, as the violations table uses the student number as a foreign key.However, only the user ID is provided during each login.

2024-11-12 11:10 UTC, kylmrcdr123 commented on src/main/java/com/rocs/osd/domain/section/Section.java
> +    private String organization;
Our Scrum Master told us to change "division" to "organization" for the clusters CBAM and CETE.

2024-11-18 04:12 UTC, closed without merging