RCPS-208: web-backend-maintenance: Refactor Backend Login Response
RoCS2024/osd-records-mgt-web-appl pull request #15
Opened 2024-11-23 03:08 UTC by JustineDaveMagnaye

RCPS 209: application-security-improvement: Fix Issue with Guest Locking Mechanism

2024-11-23 03:16 UTC, zhairanicolepacheco approved these changes

2024-11-24 01:52 UTC, PhilippaulDaganio approved these changes

2024-11-24 09:50 UTC, esdi-00 commented on src/main/java/com/rocs/osd/controller/user/UserController.java
> +    private String getUserNumber(long userId) {
this will be a performance issue. calling the database four times everytime this method is called. please consider more efficient algorithm

2024-11-24 09:51 UTC, esdi-00 approved these changes
see comment

2024-11-24 09:55 UTC, esdi-00 requested changes
see comment

2024-11-24 10:26 UTC, JustineDaveMagnaye commented on src/main/java/com/rocs/osd/controller/user/UserController.java
> +    private String getUserNumber(long userId) {
I used a switch statement to check the users role. This would make it only use a single sql query after a role has been identified

2024-11-25 10:55 UTC, esdi-00 approved these changes

2024-11-25 10:57 UTC, merged