RCPS-7 web-frontend-maintenance: Refactor Login Module
RoCS2024/osd-records-mgt-web-appl pull request #5
Opened 2024-09-29 08:30 UTC by HaroldDinglasan

2024-09-29 10:12 UTC, esdi-00 commented on FrontEnd/login-page/src/logo.svg
why is the react logo in the project? is this necessary?

2024-09-29 10:12 UTC, esdi-00 commented on FrontEnd/login-page/.vscode/settings.json
why is there vscode specific files in the project?

2024-09-29 10:13 UTC, esdi-00 requested changes
see comments

2024-09-30 10:25 UTC, HaroldDinglasan commented on FrontEnd/login-page/.vscode/settings.json
as far as i know po sir it is already built in

2024-10-02 11:20 UTC, closed without merging