Web Backedn Refactor Register
RoCS2024/osd-records-mgt-web-appl pull request #6
Opened 2024-09-29 13:26 UTC by kylmrcdr123

RCPS-103 web-backend-maintenance: Refactor Register Function. This function is for registration of student, employee, external, and guest account.

2024-10-02 12:02 UTC, esdi-00 commented on BackEnd/osd-records-mgt-appl/src/main/java/com/rocs/osd/domain/email/constant/EmailConstant.java
> +    public static final String EMAIL_SUBJECT = "Welcome to Video Rental System: Your New Password";
Video Rental System?

2024-10-02 12:05 UTC, esdi-00 commented on BackEnd/osd-records-mgt-appl/src/main/java/com/rocs/osd/utils/security/constant/SecurityConstant.java
> +    public static final String ROCS_ADMINISTRATION = "Video Rental Self Service";
Video Rental?

2024-10-02 12:05 UTC, esdi-00 commented on BackEnd/osd-records-mgt-appl/src/main/java/com/rocs/osd/utils/security/constant/SecurityConstant.java
> +    public static final String ROCS = "RoCS";
RoCS?

2024-10-02 12:06 UTC, esdi-00 commented on BackEnd/osd-records-mgt-appl/src/main/resources/application.yml
> +      ddl-auto: update
do not use ddl-update in production.

2024-10-02 12:07 UTC, esdi-00 requested changes
check comments 
provide proper documentation

2024-10-02 12:10 UTC, esdi-00 commented
Also, remove it from BackEnd folder.

2024-10-02 23:19 UTC, esdi-00 commented on src/main/java/com/rocs/osd/controller/user/UserController.java
> +    private void authenticate(String username, String password) {
no java docs for private methods

2024-10-02 23:19 UTC, esdi-00 commented on src/main/java/com/rocs/osd/controller/user/UserController.java
> +    private HttpHeaders getJwtHeader(UserPrincipal userPrincipal) {
no java docs for private methods

2024-10-02 23:20 UTC, esdi-00 commented on src/main/java/com/rocs/osd/domain/user/User.java
> +public class User implements Serializable {
missing java docs

2024-10-02 23:21 UTC, esdi-00 commented on src/main/java/com/rocs/osd/exception/constant/ExceptionConstant.java
> +public class ExceptionConstant {
missing javadocs

2024-10-02 23:21 UTC, esdi-00 commented on src/main/java/com/rocs/osd/exception/domain/EmailExistsException.java
> +public class EmailExistsException extends Exception {
missing javadocs

2024-10-02 23:26 UTC, kylmrcdr123 commented on src/main/java/com/rocs/osd/exception/domain/EmailExistsException.java
> +public class EmailExistsException extends Exception {
this is noted sir

2024-10-02 23:30 UTC, esdi-00 requested changes
check all the java docs
- no javadocs for private methods, private classes and overridden methods
- javadocs needed for public ones

2024-10-03 00:55 UTC, daiahnadine requested changes

2024-10-03 00:55 UTC, daiahnadine commented on src/main/java/com/rocs/osd/controller/user/UserController.java
> +    private void authenticate(String username, String password) {
Please avoid using technical jargon like REST and JWT Token. explain the purpose in more general terms or provide short explanation about the technical jargons you will be using.

2024-10-03 00:55 UTC, daiahnadine commented on src/main/java/com/rocs/osd/domain/email/constant/EmailConstant.java
please atleast explain smtp and starttls in more general terms

2024-10-03 00:55 UTC, daiahnadine commented on src/main/java/com/rocs/osd/domain/http/response/HttpResponse.java
use more general term

2024-10-03 00:55 UTC, daiahnadine commented on src/main/java/com/rocs/osd/utils/converter/StringListConverter.java
> + * Convert the List of Strings to a single String
what is a string? use general term in explaining it so that non technical users can also understand this

2024-10-03 00:55 UTC, daiahnadine commented on src/main/java/com/rocs/osd/utils/security/WebConfig.java
> + * WebConfig sets up CORS (Cross-Origin Resource Sharing) settings for the application.
avoid jargon or atleast provide brief explanation for this jargon. make this java doc more general.

2024-10-03 00:55 UTC, daiahnadine commented on src/main/java/com/rocs/osd/utils/security/configuration/SecurityConfiguration.java
> + * and CORS
avoid jargon or atleast provide brief explanation for CORS

2024-10-03 00:55 UTC, daiahnadine commented on src/main/java/com/rocs/osd/utils/security/constant/SecurityConstant.java
make javadoc more general

2024-10-03 00:55 UTC, daiahnadine commented on src/main/java/com/rocs/osd/utils/security/jwt/provider/token/JWTTokenProvider.java
explain atleast once the JWT token

2024-10-07 12:08 UTC, esdi-00 commented on src/main/java/com/rocs/osd/controller/employee/EmployeeController.java
> +    @GetMapping("/employees")
mapping is Employee/employees? seems redundant

2024-10-07 12:08 UTC, esdi-00 commented on src/main/java/com/rocs/osd/controller/employee/EmployeeController.java
> +    @GetMapping("/employee/{employeeNumber}")
fix mapping

2024-10-07 12:14 UTC, kylmrcdr123 commented on src/main/java/com/rocs/osd/controller/employee/EmployeeController.java
> +    @GetMapping("/employee/{employeeNumber}")
This is noted sir

2024-10-07 13:38 UTC, zhairanicolepacheco approved these changes

2024-10-08 03:25 UTC, JustineDaveMagnaye approved these changes

2024-10-08 14:44 UTC, PhilippaulDaganio approved these changes

2024-10-11 14:19 UTC, rosellemarithe approved these changes
all good, it is working

2024-10-13 06:47 UTC, daiahnadine approved these changes

2024-10-13 09:09 UTC, esdi-00 approved these changes

2024-10-13 09:25 UTC, merged