Offense Functionality
RoCS2024/osd-records-mgt-web-appl pull request #8
Opened 2024-10-15 00:58 UTC by kylmrcdr123

RCPS-77 web-backend-maintenance: Refactor View All Offenses Function 
RCPS-78 web-backend-maintenance: Refactor Add Offense Function
RCPS-79 web-backend-maintenance: Refactor Update Offense Function

2024-10-15 05:33 UTC, esdi-00 commented on src/main/java/com/rocs/osd/controller/offense/OffenseController.java
> +@RequestMapping("/Offense")
still capital?

2024-10-15 05:34 UTC, esdi-00 requested changes
see comment

2024-10-15 11:02 UTC, JustineDaveMagnaye approved these changes

2024-10-15 11:40 UTC, zhairanicolepacheco approved these changes

2024-10-16 02:38 UTC, esdi-00 approved these changes

2024-10-16 11:14 UTC, PhilippaulDaganio approved these changes

2024-10-16 11:15 UTC, PhilippaulDaganio approved these changes

2024-10-17 15:10 UTC, kylematalog approved these changes
all goods

2024-10-17 15:11 UTC, merged